const fs = require('fs');
const files = {
  vi: '/home/dev_ntd/Know_Block/Know_Ledge_Block/FE/messages/vi.json',
  en: '/home/dev_ntd/Know_Block/Know_Ledge_Block/FE/messages/en.json',
  ja: '/home/dev_ntd/Know_Block/Know_Ledge_Block/FE/messages/ja.json',
};

const keys = {
  vi: {
    "addStory": "Tạo tin mới",
    "textStory": "Tin Chữ",
    "mediaStory": "Ảnh/Video",
    "preview": "Khung xem trước",
    "cancel": "Hủy bỏ",
    "postStory": "Đăng tin",
    "uploadingStory": "Đang tải lên tin",
    "startTyping": "Bắt đầu nhập chữ...",
    "chooseBackground": "Chọn Màu Nền",
    "uploadMedia": "Tải Ảnh/Video Lên",
    "dragAndDropOrClick": "Kéo thả tệp vào đây hoặc nhấn để chọn",
    "supportedFormats": "Hỗ trợ JPG, PNG, GIF, MP4. Tối đa 50MB",
    "text": "Chữ",
    "stickers": "Nhãn dán",
    "filters": "Bộ lọc",
    "draw": "Vẽ tay",
    "music": "Âm nhạc",
    "addNewText": "Thêm chữ mới",
    "textOverlayList": "Danh sách chữ đè",
    "empty": "Trống",
    "textContent": "Nội dung chữ",
    "enterText": "Nhập chữ...",
    "font": "Font chữ",
    "size": "Kích cỡ",
    "textColor": "Màu chữ",
    "backgroundColor": "Màu nền",
    "transparent": "Trong suốt",
    "white": "Trắng",
    "black": "Đen",
    "blue": "Xanh lam",
    "yellow": "Vàng",
    "red": "Đỏ",
    "green": "Xanh lá",
    "addTextInstruction": "Hãy nhấn \"Thêm chữ mới\" để viết chữ kéo thả tùy ý trên tin!",
    "clickStickerInstruction": "Nhấn vào bất kỳ biểu tượng nào dưới đây để thêm vào tin",
    "enableBrush": "Bật cọ vẽ tay",
    "brushColor": "Màu cọ",
    "undo": "Hoàn tác",
    "clearCanvas": "Xóa toàn bộ",
    "drawInstruction": "Hãy bật nút \"Bật cọ vẽ tay\" để vẽ tự do lên tin!",
    "musicPreviewNotSupport": "Thiết bị của bạn không hỗ trợ phát thử âm nhạc ZingMp3 trong trình duyệt này.",
    "searchZingMp3": "Tìm bài hát trên ZingMp3...",
    "noMusicFound": "Không tìm thấy bài hát nào.",
    "lyrics": "Lời bài hát",
    "musicStartOffset": "Điểm bắt đầu phát nhạc",
    "musicOverlayType": "Kiểu hiển thị",
    "none": "Không hiển thị",
    "fileTooLarge": "Dung lượng tệp vượt quá giới hạn 50MB!",
    "videoTooLong": "Thời lượng video vượt quá giới hạn 30 giây! Vui lòng chọn video ngắn hơn.",
    "confirmClose": "Bạn có chắc chắn muốn đóng? Bản nháp hiện tại của bạn sẽ bị xóa bỏ.",
    "postFailed": "Đăng tin thất bại. Vui lòng thử lại!",
    "musicLoadError": "Lỗi tải thông tin bài hát từ ZingMp3. Vui lòng thử lại!",
    "musicNotSupport": "Không thể tải stream bài hát này từ ZingMp3 (có thể là bài hát bản quyền hoặc VIP). Vui lòng chọn bài khác!",
    "confirmRestore": "Phát hiện bản nháp chưa hoàn thành. Bạn có muốn khôi phục lại không?"
  },
  en: {
    "addStory": "Create Story",
    "textStory": "Text Story",
    "mediaStory": "Photo/Video",
    "preview": "Preview",
    "cancel": "Cancel",
    "postStory": "Post Story",
    "uploadingStory": "Uploading Story",
    "startTyping": "Start typing...",
    "chooseBackground": "Choose Background",
    "uploadMedia": "Upload Photo/Video",
    "dragAndDropOrClick": "Drag and drop file here or click to select",
    "supportedFormats": "Supports JPG, PNG, GIF, MP4. Max 50MB",
    "text": "Text",
    "stickers": "Stickers",
    "filters": "Filters",
    "draw": "Draw",
    "music": "Music",
    "addNewText": "Add New Text",
    "textOverlayList": "Text Overlay List",
    "empty": "Empty",
    "textContent": "Text Content",
    "enterText": "Enter text...",
    "font": "Font",
    "size": "Size",
    "textColor": "Text Color",
    "backgroundColor": "Background Color",
    "transparent": "Transparent",
    "white": "White",
    "black": "Black",
    "blue": "Blue",
    "yellow": "Yellow",
    "red": "Red",
    "green": "Green",
    "addTextInstruction": "Click 'Add New Text' to add drag-and-drop text to your story!",
    "clickStickerInstruction": "Click on any sticker below to add to your story",
    "enableBrush": "Enable Brush",
    "brushColor": "Brush Color",
    "undo": "Undo",
    "clearCanvas": "Clear Canvas",
    "drawInstruction": "Turn on 'Enable Brush' to draw freely on your story!",
    "musicPreviewNotSupport": "Your browser does not support audio preview for ZingMp3.",
    "searchZingMp3": "Search song on ZingMp3...",
    "noMusicFound": "No songs found.",
    "lyrics": "Lyrics",
    "musicStartOffset": "Music Start Point",
    "musicOverlayType": "Display Style",
    "none": "None",
    "fileTooLarge": "File size exceeds 50MB limit!",
    "videoTooLong": "Video duration exceeds 30 seconds limit! Please choose a shorter video.",
    "confirmClose": "Are you sure you want to close? Your current draft will be deleted.",
    "postFailed": "Failed to post story. Please try again!",
    "musicLoadError": "Error loading song info from ZingMp3. Please try again!",
    "musicNotSupport": "Cannot load audio stream from ZingMp3 (might be copyrighted or VIP). Please choose another song!",
    "confirmRestore": "Found an unfinished draft. Do you want to restore it?"
  },
  ja: {
    "addStory": "ストーリーを作成",
    "textStory": "テキストストーリー",
    "mediaStory": "写真/動画",
    "preview": "プレビュー",
    "cancel": "キャンセル",
    "postStory": "ストーリーを投稿",
    "uploadingStory": "ストーリーをアップロード中",
    "startTyping": "入力してください...",
    "chooseBackground": "背景を選択",
    "uploadMedia": "写真/動画をアップロード",
    "dragAndDropOrClick": "ここにファイルをドラッグ＆ドロップするか、クリックして選択してください",
    "supportedFormats": "サポート: JPG, PNG, GIF, MP4。最大 50MB",
    "text": "テキスト",
    "stickers": "ステッカー",
    "filters": "フィルター",
    "draw": "描画",
    "music": "音楽",
    "addNewText": "新しいテキストを追加",
    "textOverlayList": "テキストリスト",
    "empty": "空",
    "textContent": "テキスト内容",
    "enterText": "テキストを入力...",
    "font": "フォント",
    "size": "サイズ",
    "textColor": "テキスト色",
    "backgroundColor": "背景色",
    "transparent": "透明",
    "white": "白",
    "black": "黒",
    "blue": "青",
    "yellow": "黄",
    "red": "赤",
    "green": "緑",
    "addTextInstruction": "「新しいテキストを追加」をクリックして、ストーリーにテキストを追加してください！",
    "clickStickerInstruction": "下のステッカーをクリックしてストーリーに追加してください",
    "enableBrush": "ブラシを有効にする",
    "brushColor": "ブラシ色",
    "undo": "元に戻す",
    "clearCanvas": "すべてクリア",
    "drawInstruction": "「ブラシを有効にする」をオンにして、ストーリーに自由に描いてください！",
    "musicPreviewNotSupport": "お使いのブラウザはZingMp3の音声プレビューをサポートしていません。",
    "searchZingMp3": "ZingMp3で曲を検索...",
    "noMusicFound": "曲が見つかりませんでした。",
    "lyrics": "歌詞",
    "musicStartOffset": "音楽の開始位置",
    "musicOverlayType": "表示スタイル",
    "none": "なし",
    "fileTooLarge": "ファイルサイズが50MBの制限を超えています！",
    "videoTooLong": "動画の長さが30秒の制限を超えています！短い動画を選択してください。",
    "confirmClose": "本当に閉じますか？現在の下書きは削除されます。",
    "postFailed": "ストーリーの投稿に失敗しました。もう一度お試しください！",
    "musicLoadError": "ZingMp3から曲情報を読み込めませんでした。もう一度お試しください！",
    "musicNotSupport": "ZingMp3からオーディオストリームを読み込めませんでした（著作権またはVIPの可能性があります）。別の曲を選択してください！",
    "confirmRestore": "未完成の下書きが見つかりました。復元しますか？"
  }
};

for (const lang of Object.keys(files)) {
  const file = files[lang];
  let data = JSON.parse(fs.readFileSync(file, 'utf8'));
  
  if (!data.story) data.story = {};
  data.story = { ...data.story, ...keys[lang] };
  
  fs.writeFileSync(file, JSON.stringify(data, null, 2), 'utf8');
  console.log('Updated ' + file);
}
