export enum CloseReason {
  EMPTY_ROOM = 'EMPTY_ROOM',
  NO_PLAYER_JOIN = 'NO_PLAYER_JOIN',
  IDLE_TIMEOUT = 'IDLE_TIMEOUT',
  ALL_SIT_OUT = 'ALL_SIT_OUT',
  OWNER_TIMEOUT = 'OWNER_TIMEOUT',
  ROOM_EXPIRED = 'ROOM_EXPIRED',
}
